# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.23.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.23.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/likejun/ProgrammingBasics/cpp-ch2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/likejun/ProgrammingBasics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.23.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.23.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/likejun/ProgrammingBasics/CMakeFiles /Users/likejun/ProgrammingBasics//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/likejun/ProgrammingBasics/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simple

# Build rule for target.
simple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple
.PHONY : simple

# fast build rule for target.
simple/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple.dir/build.make CMakeFiles/simple.dir/build
.PHONY : simple/fast

#=============================================================================
# Target rules for targets named binary

# Build rule for target.
binary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 binary
.PHONY : binary

# fast build rule for target.
binary/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary.dir/build.make CMakeFiles/binary.dir/build
.PHONY : binary/fast

#=============================================================================
# Target rules for targets named diamond

# Build rule for target.
diamond: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 diamond
.PHONY : diamond

# fast build rule for target.
diamond/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diamond.dir/build.make CMakeFiles/diamond.dir/build
.PHONY : diamond/fast

binary.o: binary.cpp.o
.PHONY : binary.o

# target to build an object file
binary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary.dir/build.make CMakeFiles/binary.dir/binary.cpp.o
.PHONY : binary.cpp.o

binary.i: binary.cpp.i
.PHONY : binary.i

# target to preprocess a source file
binary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary.dir/build.make CMakeFiles/binary.dir/binary.cpp.i
.PHONY : binary.cpp.i

binary.s: binary.cpp.s
.PHONY : binary.s

# target to generate assembly for a file
binary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary.dir/build.make CMakeFiles/binary.dir/binary.cpp.s
.PHONY : binary.cpp.s

diamond.o: diamond.cpp.o
.PHONY : diamond.o

# target to build an object file
diamond.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diamond.dir/build.make CMakeFiles/diamond.dir/diamond.cpp.o
.PHONY : diamond.cpp.o

diamond.i: diamond.cpp.i
.PHONY : diamond.i

# target to preprocess a source file
diamond.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diamond.dir/build.make CMakeFiles/diamond.dir/diamond.cpp.i
.PHONY : diamond.cpp.i

diamond.s: diamond.cpp.s
.PHONY : diamond.s

# target to generate assembly for a file
diamond.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diamond.dir/build.make CMakeFiles/diamond.dir/diamond.cpp.s
.PHONY : diamond.cpp.s

simple.o: simple.cpp.o
.PHONY : simple.o

# target to build an object file
simple.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple.dir/build.make CMakeFiles/simple.dir/simple.cpp.o
.PHONY : simple.cpp.o

simple.i: simple.cpp.i
.PHONY : simple.i

# target to preprocess a source file
simple.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple.dir/build.make CMakeFiles/simple.dir/simple.cpp.i
.PHONY : simple.cpp.i

simple.s: simple.cpp.s
.PHONY : simple.s

# target to generate assembly for a file
simple.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple.dir/build.make CMakeFiles/simple.dir/simple.cpp.s
.PHONY : simple.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... binary"
	@echo "... diamond"
	@echo "... simple"
	@echo "... binary.o"
	@echo "... binary.i"
	@echo "... binary.s"
	@echo "... diamond.o"
	@echo "... diamond.i"
	@echo "... diamond.s"
	@echo "... simple.o"
	@echo "... simple.i"
	@echo "... simple.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

